# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\network_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from tools.basic import Basic
from enums.unit import *
from enums.module_type import *
from enums.input_type import *
from enums.args import *


class Model:
    def generate_window(self, widget, data):
        self.basic = Basic(widget)

        for value in data.values():
            # 创建标签
            self.basic.create("label", value[0], True, False, value[1])
            # 创建内容
            if value[2] == "":  # 如果没有单位
                self.basic.create(value[3], self.toArray(value[4]), True)
            else:
                child1 = self.basic.createChild("combox", self.toArray(value[2]), False)
                child2 = self.basic.createChild(value[3], self.toArray(value[4]), True)
                self.basic.createLayout([child1, child2])

        self.modules = self.basic.modules

        # basic.leader.currentIndexChanged.connect(
        #     lambda index: basic.updateValues(index)
        # )

        # 存放标签和值
        self.labels = self.basic.labels
        self.values = self.basic.modules

        return self.basic

    def toArray(self, text):
        array = text.split(",")
        return array

    def getBasic(self):
        return self.basic
