# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\network_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from tool import basic


class Model:
    def __init__(self):
        self.values = None
        self.labels = None
        self.modules = None
        self.base = None

    def generate_window(self, widget, data):
        self.base = basic.Basic(widget)

        for value in data.values():
            # 创建标签
            self.base.create("label", value[0], True, False, value[1])
            # 创建内容
            if value[2] == "":  # 如果没有单位
                self.base.create(
                    value[3], self.to_array(value[4]), True, input_type=value[5]
                )
            else:
                child1 = self.base.create_child(
                    "combox", self.to_array(value[2]), False, value[5]
                )
                child2 = self.base.create_child(
                    value[3], self.to_array(value[4]), True, value[5]
                )
                self.base.create_layout([child1, child2])

        self.modules = self.base.modules

        # basic.leader.currentIndexChanged.connect(
        #     lambda index: basic.updateValues(index)
        # )

        # 存放标签和值
        self.labels = self.base.labels
        self.values = self.base.modules

        return self.base

    def to_array(self, text):
        array = text.split(",")
        return array

    def getBasic(self):
        return self.base
